name: edl

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  download-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download files
      run: |
        sudo apt update
        sudo apt install tar build-essential file libncurses-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3 python3-full python3-venv -y
        mkdir -p downloads
        cd downloads
        wget -O Ubuntu_EDL.iso https://ava6.androidfilehost.com/dl/u2tWmXKFGtNMwqLo3ZY35g/1760037834/15664248565197184488/re_livedvdV4.iso?
           
    - name: Determine release tag
      id: get_tag
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          TAG_NAME="${{ github.event.release.tag_name }}"
        else
          TAG_NAME="ubuntu-edl"
        fi
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Delete existing release assets
      uses: actions/github-script@v7
      with:
        script: |
          const { data: releases } = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          
          const targetRelease = releases.find(release => release.tag_name === '${{ steps.get_tag.outputs.tag_name }}');
          
          if (targetRelease) {
            console.log(`Found release with tag: ${{ steps.get_tag.outputs.tag_name }}`);
            console.log(`Release ID: ${targetRelease.id}`);
            
            const { data: assets } = await github.rest.repos.listReleaseAssets({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: targetRelease.id
            });
            
            console.log(`Found ${assets.length} assets to delete`);
            
            for (const asset of assets) {
              console.log(`Deleting asset: ${asset.name} (ID: ${asset.id})`);
              await github.rest.repos.deleteReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                asset_id: asset.id
              });
            }
            
            console.log('All existing assets deleted');
          } else {
            console.log(`No release found with tag: ${{ steps.get_tag.outputs.tag_name }}`);
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload files to existing release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_tag.outputs.tag_name }}
        files: |
          downloads/*.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
